### ISSUE TITLE
Pavilion Name - edit name

### ISSUE THREAD

**Issue by fakeshop** [BangkokBiennial/bangkok-biennial-platform#13]
Theres a problem that the 'short description' and 'Pavilion name', theres no way to edit/correct the information so even a user tries to update, the info displays as originally done upon initial registration, it stays locked in.
using American Pavilion as a test case guinea pig ;-0 

It seems we need to upgrade/add a form - field for this function in general, and especially for editing published information once the Pavilion has passed the approve stage.

**Comment by fakeshop** [comment]
![AmericanPavilionwrongname](https://user-images.githubusercontent.com/52246477/105469949-88e8b280-5ccb-11eb-9d07-d99aef4fbdc6.jpg)
![Edit pavilion detail after](https://user-images.githubusercontent.com/52246477/105470083-b170ac80-5ccb-11eb-9dcb-a1a68fb38fc1.jpg)

**Comment by christopheradams** [comment]
This is a sensible request. Currently the Pavilion detail edit page is missing fields for `pavilionName` and `pavilionBriefDescription`. What would it take to add them?

**Comment by dodadoa** [comment]
@fakeshop @christopheradams sorry for late reply, I will work on it this weekend.

**Comment by dodadoa** [comment]
@fakeshop I just made the pavilion name and pavilion short description to the edit page (took more time than I thought 😅🙏), could you please check ?
